default_language_version:
  python: python3

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

default_stages:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args:
          - --number
        additional_dependencies:
          - mdformat-gfm
          - mdformat-web
          - mdformat-ruff
          - mdformat-config
          - mdformat-tables
          - mdformat-footnote
          - mdformat_frontmatter
          - mdformat-pyproject
          - mdformat-mkdocs[recommended]
