services:
  frontend:
    image: mtkomcr.mediatek.inc/srv-aith/agent-canvas
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    env_file:
      - .env
    command:
      - yarn
      - start
      - --host=0.0.0.0
      - --port=3000
    ports:
      - 8787:3000
    volumes:
      - ./.env:/app/.env
    pull_policy: always
    restart: always
